// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iccqqpuxyeaamurhvbbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljY3FxcHV4eWVhYW11cmh2YmJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzUyNDcsImV4cCI6MjA2NDMxMTI0N30.2EyrdcT-V8_Z4NHClZLHvtYNLr1tBEAdNnCC4MjiQc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);